authproject/api/urls.py
from django.urls import path,include
from api import views


urlpatterns = [
     path('articles/',views.article_list),
     path('categories/',views.category_list),
     path('article/<int:article_id>',views.article),
]

authproject/authapp/urls.py
from django.contrib import admin
from django.urls import path,include
from authapp import views

urlpatterns = [
    path('sign_up/',views.sign_up),
]

authproject/authproject/urls.py
from django.contrib import admin
from django.urls import path,include
from authapp import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('authapp.urls')),
    path('blog/',include('blog.urls')),
    path('api/',include('api.urls'))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

print(settings.INSTALLED_APPS)

authproject/blog/urls.py
from django.urls import path,include
from blog import views

app_name = "blog"

urlpatterns = [
    path('',views.listing),
    path('<int:blog_id>',views.detail,name = "blog_detail")
]

authproject/api/models.py
from django.db import models

# Create your models here.

authproject/authapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

authproject/blog/models.py
from django.db import models

class User(models.Model):
    first_name = models.CharField(max_length = 20,blank = False)
    last_name = models.CharField(max_length = 20,blank = False)
    email = models.EmailField(max_length = 100,blank = False)
    password = models.CharField(max_length = 20,blank= False)    #add validator
    age = models.IntegerField(blank=True)     #add validator

    def __str__(self):
        return self.first_name+ " " + self.last_name

class Author(User):
    is_author = models.BooleanField()
    writing_skills = models.TextField(blank=True)
    mobile = models.CharField(max_length = 15,blank=True)      #add validator

    def __str__(self):
        return "(Author) " + self.first_name + " " + self.last_name

class ArticleCategory(models.Model):
    name = models.CharField(max_length = 20,blank = False)
    description = models.TextField(blank=True)
    image  = models.ImageField(upload_to="blog/category/",blank=True)

    def __str__(self):
        return self.name

class Article(models.Model):
    title = models.CharField(max_length=50,blank=False)
    description = models.TextField(blank=False)
    long_description = models.TextField(blank=False)

    publish_date = models.DateTimeField(blank = True,null = True)
    expriry_date = models.DateTimeField(blank = True,null = True)
    image = models.ImageField(upload_to = "blog/article/",blank = True)

    date_created  = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    #many to one relationship with author
    author = models.ForeignKey(Author,on_delete=models.CASCADE)
    #many to many relationship with articlecategory
    article_category = models.ManyToManyField(ArticleCategory,through='ArticleCategoryJoin')

    class Meta():
        ordering = ['-date_modified']

    def __str__(self):
        return "(" +  str(self.id) + ") " +self.title

class ArticleCategoryJoin(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE)
    category = models.ForeignKey(ArticleCategory,on_delete=models.CASCADE)

    def __str__(self):
        return self.article.title[:30] + " - " + self.category.name

authproject/authapp/forms/sign_up.py
from django.contrib.auth.models import User
from django.forms import ModelForm

class SignUpForm(ModelForm):
    class Meta:
        model = User
        fields = ['username','password','email','first_name','last_name']

authproject/api/views.py
from django.shortcuts import render
from blog.models import Article,ArticleCategory
from api import serializer
from django.http import JsonResponse
from rest_framework import status
# Create your views here.

def article_list(request):
    articles = Article.objects.all().order_by('-id')
    articles_serializer = serializer.ArticleListSerializer(articles,many=True)
    print(type(articles_serializer.data))
    print(articles.count())

    return_dict = {
        "count" : articles.count(),
        "data" : articles_serializer.data
    }

    return JsonResponse(return_dict,status = status.HTTP_200_OK)

def category_list(request):
    categories = ArticleCategory.objects.all()
    cat_serializer = serializer.CategorySerializer(categories,many=True)

    return JsonResponse(cat_serializer.data,safe = False,status= status.HTTP_200_OK)


def article(request,article_id):
    article = Article.objects.get(pk=article_id)
    article_serializer = serializer.ArticleSerializer(article)
    return JsonResponse(article_serializer.data,safe=False)

authproject/authapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.models import User
from authapp.forms.sign_up import SignUpForm
import sys
# Create your views here.


def sign_up(request):

    if(request.method == "POST"):
        sign_up_form = SignUpForm(request.POST)
        if(sign_up_form.is_valid):
            username = request.POST.get('username')
            password = request.POST.get('password')
            email = request.POST.get('email')
            first_name = request.POST.get('first_name')
            last_name = request.POST.get('last_name')
            user = User()
            print(type(request.POST.get('email1')))
            print(request.POST.get('email1'))
            sys.exit(0)
            user.set_password(password)
            user.username = username
            user.email = email
            user.save()

    else:
        sign_up_form = SignUpForm()
    context = {
        'form': sign_up_form
    }
    return render(request, 'authapp/sign_up.html', context)

authproject/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from blog.models import Article, ArticleCategory, ArticleCategoryJoin, Author
from django.core.paginator import Paginator
import sys
# Create your views here.


def listing(request):
    print(dir(request))

    print(request.method)
    print(request.get_host())
    print(request.get_port())
    print(request.session)
    all_articles = Article.objects.all()
    paginator = Paginator(all_articles, 2)

    requestedPage = request.GET.get('page')
    articles = paginator.get_page(requestedPage)

    # fetching all the categories
    all_categories = ArticleCategory.objects.all()
    categories_dict = {}
    for category in all_categories:
        article_count = ArticleCategoryJoin.objects.filter(category=category).count()
        categories_dict[category.id] = {"category": category, "article_count": article_count}

    # fetching all the authors
    all_authors = Author.objects.all()
    authors_dict = {}
    for author in all_authors:
        article_count = author.article_set.all().count()        
        authors_dict[author.id] = {'author': author, "article_count": article_count}

    context = {
        'articles': articles,
        'categories_dict': categories_dict,
        'authors_dict': authors_dict,
    }
    return render(request, 'blog/listing.html', context)


def detail(request, blog_id):
    all_articles = Article.objects.all()
    paginator = Paginator(all_articles, 2)

    # fetching all the categories
    all_categories = ArticleCategory.objects.all()
    categories_dict = {}
    for category in all_categories:
        article_count = ArticleCategoryJoin.objects.filter(category=category).count()
        categories_dict[category.id] = {
            "category": category, "article_count": article_count}

    # fetching all the authors
    all_authors = Author.objects.all()
    authors_dict = {}
    for author in all_authors:
        article_count = author.article_set.all().count()
        authors_dict[author.id] = {'author': author, "article_count": article_count}

    try:
        article = Article.objects.get(id=blog_id)

        context = {
            'article': article,
            'categories_dict': categories_dict,
            'authors_dict': authors_dict,
        }

        return render(request, 'blog/detail.html', context)
    except Article.DoesNotExist:
        return render(request, 'blog/article_not_found.html')

authproject/templates/authapp/sign_up.html
<!DOCTYPE <!DOCTYPE html>
<html>

<head>
    <title>Page Title</title>
</head>

<body>
    <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Sign-Up">
        </form>
</body>

</html>

authproject/templates/blog/article_not_found.html
Article does not exit

authproject/templates/blog/detail.html
{% extends 'blog/layout.html' %} 

{% block content %}

<div style="background-color:#e5e5e5;padding:15px;text-align:center;">
    <h1>Hello World</h1>
</div>

<div style="overflow:auto">

    {% include 'blog/include/left_navigation.html' %}

    {{ article }}

    {% include 'blog/include/right_description.html' %}

</div>  
<div style="background-color:#e5e5e5;text-align:center;padding:10px;margin-top:7px;">© copyright w3schools.com</div>

{% endblock %}

authproject/templates/blog/include/blog_looping.html
<div class="main">
    {% for article in articles %}
    <div>
        <img src="{{ article.image.url }}" width="100" height="100">
        <a href="{% url 'blog:blog_detail' article.id  %}"><h2>{{ article.title }}</h2></a>
        <p> {{ article.date_created }} </p>
        <p>{{ article.description }}</p>
    </div>
    {% endfor %}

    {% include 'blog/include/pagination.html' %}

</div>

authproject/templates/blog/include/left_navigation.html
<div class="menu">
    <h2 style="text-decoration: underline">Categories</h2>

    {% for cat_id,cat_dict in categories_dict.items %}
    <a href="?category={{ cat_id }}">{{ cat_dict.category }} ({{ cat_dict.article_count }}) </a>
    {% endfor %} 
    
    <h2 style="text-decoration: underline">Authors</h2>

    {% for art_id,art_dict in authors_dict.items %}
    <a href="?author={{ art_id }}">{{ art_dict.author.first_name }} ({{ art_dict.article_count }}) </a>
    {% endfor %}

</div>

authproject/templates/blog/include/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if articles.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ articles.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ articles.number }} of {{ articles.paginator.num_pages }}.
        </span>

        {% if articles.has_next %}
        <a href="?page={{ articles.next_page_number }}">next</a>
        <a href="?page={{ articles.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

authproject/templates/blog/include/right_description.html
<div class="right">
    <h2>About</h2>
    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>
</div>

authproject/templates/blog/layout.html
<!DOCTYPE html> {% load static %}
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
</head>

<body style="font-family:Verdana;color:#aaaaaa;">


    {% block content %}
    {% endblock %}


</body>

</html>

authproject/templates/blog/listing.html
<!DOCTYPE html> {% load static %}
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css " %}">
</head>

<body style="font-family:Verdana;color:#aaaaaa;">

    <div style="background-color:#e5e5e5;padding:15px;text-align:center;">
        <h1>Hello World</h1>
    </div>

    <div style="overflow:auto">
        <div class="menu">
            <a href="#">Link 1</a>
            <a href="#">Link 2</a>
            <a href="#">Link 3</a>
            <a href="#">Link 4</a>
        </div>

        <div class="main">
            {% for article in articles %}
            <div>
                <img src="{{ article.image.url }}">
                <h2>{{ article.title }}</h2>
                <p>{{ article.description }}</p>
            </div>
            {% endfor %}            
        </div>


        <div class="right">
            <h2>About</h2>
            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>
        </div>
    </div>

    <div style="background-color:#e5e5e5;text-align:center;padding:10px;margin-top:7px;">© copyright w3schools.com</div>

</body>

</html>